import type { Recipe } from "@ai-recipes/shared";

/**
 * Format a recipe as plain text for export/sharing
 */
export function formatRecipeAsText(recipe: Recipe): string {
  let text = `${recipe.name}\n\n`;

  // Ingredients section
  text += "Ingredients:\n";
  recipe.ingredients.forEach((ingredient) => {
    text += `• ${ingredient}\n`;
  });

  text += "\n";

  // Instructions section
  text += "Instructions:\n";
  recipe.instructions.forEach((instruction, index) => {
    text += `${index + 1}. ${instruction}\n`;
  });

  // Footer
  text += "\n---\nGenerated by AI Recipes";

  return text;
}
